# Generated by Django 4.2.20 on 2025-04-07 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_family_familytag_delete_families'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familytag',
            options={'verbose_name': 'Family Member', 'verbose_name_plural': 'Family Members'},
        ),
        migrations.RenameField(
            model_name='familytag',
            old_name='family_id',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='familytag',
            old_name='member_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='familytag',
            unique_together={('family', 'user')},
        ),
        migrations.CreateModel(
            name='FridgeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_contents', to='inventory.family')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='inventory.itemsdetails')),
            ],
            options={
                'verbose_name': 'Fridge Content',
                'verbose_name_plural': 'Fridge Contents',
            },
        ),
    ]
